services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: talk-keycloak
    volumes: 
      - ./application:/app
    ports: 
      - '8080:8080'
    restart: unless-stopped    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy  
    networks:
      - internal 
  jsapp:
    container_name: talk-js-app
    build: ./js-app/
    networks:
      - internal
    ports:
      - '8000:8000'
    volumes: 
      - ./js-app/application:/app/
    depends_on:
      - keycloak
networks:
  internal:
    driver: bridge