services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: talk-keycloak
    restart: unless-stopped    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy  
    networks:
      - internal 
  jsapp:
    container_name: talk-js-app
    build: ./js-app/
    networks:
      - internal
    expose: 
      - 8000
    depends_on:
      - keycloak
  nginx:
    container_name: talk-nginx
    build: ./nginx/
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - keycloak
      - jsapp
networks:
  internal:
    driver: bridge